Added AnonInfo and Info::registerByReflection
SOF3/InfoAPI pull request #10
Opened 2021-12-29 14:41 UTC by SOF3

2022-02-09 18:31 UTC, Endermanbugzjfc requested changes

2022-02-09 18:31 UTC, Endermanbugzjfc commented on tests/AnonInfoTest.php
> +	}
Should add a test for indexed array (`[new NumberInfo(), new NumberInfo()]`, `{0 ordinal} {test.1 ordinal}`).

2022-02-09 18:31 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/ContextInfo.php
> + * @link AnonInfo
Why not `@see`? I thought `@link` is only used to "embed" a `@see`.

2022-02-09 18:31 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/Info.php
> +				throw new ReflectionException("Property $property is untyped");
$type could also be union types, I think the message should change to "Property $property does not have a valid type". Or user might confuse.

2022-02-09 18:31 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/Info.php
> +				throw new ReflectionException("Property $property is untyped");
Same for here.

2022-02-10 04:33 UTC, SOF3 commented on tests/AnonInfoTest.php
> +	}
Why would you want to use numeric names?

2022-02-10 04:33 UTC, SOF3 commented on src/SOFe/InfoAPI/ContextInfo.php
> + * @link AnonInfo
```suggestion
 * @see AnonInfo
```

2022-02-10 04:34 UTC, SOF3 commented on src/SOFe/InfoAPI/Info.php
> +				throw new ReflectionException("Property $property is untyped");
Please suggest a better message. Use the suggestion button in the conversation editor.

2022-02-10 08:33 UTC, Endermanbugzjfc commented on tests/AnonInfoTest.php
> +	}
Maybe a list of players. But never mind because there's is no looping system for info.

2022-02-11 15:17 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/Info.php
> +				throw new ReflectionException("Property $property is untyped");
```suggestion
				throw new ReflectionException("Property $property does not have a valid type");
```

2022-02-11 15:18 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/Info.php
> +				throw new ReflectionException("Property $property is untyped");
```suggestion
				throw new ReflectionException("Property $property does not have a valid type");
```

2022-02-12 09:56 UTC, Endermanbugzjfc approved these changes

2022-02-12 10:32 UTC, merged