Fix case is not insensitive
SOF3/InfoAPI pull request #14
Opened 2022-02-09 18:59 UTC by Endermanbugzjfc

2022-02-10 04:31 UTC, SOF3 requested changes
Also add tests for infos with upper and mixed case names

2022-02-10 04:31 UTC, SOF3 commented on tests/CaseInsensitiveTest.php
> +	private function provideInfo(InfoAPI $api) : void {
Methods should always be static if it doesn't use `$this`.

2022-02-11 16:11 UTC, Endermanbugzjfc commented on tests/CaseInsensitiveTest.php
> +	private function provideInfo(InfoAPI $api) : void {
```suggestion
	private static function provideInfo(InfoAPI $api) : void {
```

2022-02-12 03:36 UTC, SOF3 commented
I don't think ChildName is the correct place to fix this. Only the actual pathfinding logic should be affected.

2022-02-12 03:46 UTC, SOF3 approved these changes

2022-02-12 03:46 UTC, merged