Added server ticks per second in common info
SOF3/InfoAPI pull request #20
Opened 2022-03-31 18:12 UTC by Endermanbugzjfc

2022-04-01 03:17 UTC, SOF3 requested changes

2022-04-01 03:17 UTC, SOF3 commented on src/SOFe/InfoAPI/CommonInfo.php
> +		$maxTps = 20;
This should be a constant not a variable.

Also, is this constant already in PocketMine?

2022-04-01 03:17 UTC, SOF3 commented on src/SOFe/InfoAPI/CommonInfo.php
> +				max($info->getValue()->getTicksPerSecond(), $maxTps),
Why `max()` here?

2022-04-02 09:05 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/CommonInfo.php
> +				max($info->getValue()->getTicksPerSecond(), $maxTps),
> Why `max()` here?

I think PocketMine-MP's ticks per second are buggy and sometimes can go beyond 20. And I afraid this could cause some problem when it gets passed into ratio info.

2022-04-02 11:18 UTC, SOF3 commented on src/SOFe/InfoAPI/CommonInfo.php
> +				max($info->getValue()->getTicksPerSecond(), $maxTps),
RatioInfo never guaranteed to be smaller than 1.
I don't think it matters to have >20 ticks anyway

2022-04-03 13:44 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/CommonInfo.php
> +		$maxTps = 20;
> This should be a constant not a variable.
> 
> Also, is this constant already in PocketMine?

Pocketmine also hard coded it, so I think it is fine.
https://github.com/pmmp/PocketMine-MP/blob/6bea2961d94c09779b1eb922894b4f18e3b8b35d/src/Server.php#L1801
```php
		$idx = $this->tickCounter % 20;
```

2022-04-03 13:45 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/CommonInfo.php
> +				max($info->getValue()->getTicksPerSecond(), $maxTps),
> RatioInfo never guaranteed to be smaller than 1. I don't think it matters to have >20 ticks anyway

Maybe I delete the max().

2022-08-10 19:13 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/CommonInfo.php
> +		$maxTps = 20;
https://github.com/pmmp/PocketMine-MP/issues/5214 reminds me of this.

2022-08-10 19:13 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/CommonInfo.php
> +				max($info->getValue()->getTicksPerSecond(), $maxTps),
```suggestion
		InfoAPI::provideInfo(self::class, RatioInfo::class, "infoapi.server.tps",
			fn($info) => new RatioInfo(
				$info->getValue()->getTicksPerSecond(),
```

2022-08-10 19:13 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/CommonInfo.php
> +				$maxTps
```suggestion
				20
```

2022-08-10 19:15 UTC, Endermanbugzjfc commented
https://github.com/pmmp/PocketMine-MP/issues/5214 reminds me of this.

2022-08-11 02:55 UTC, SOF3 approved these changes

2022-08-11 03:25 UTC, merged