Comment to help ppl understand.
SOF3/InfoAPI pull request #27
Opened 2022-12-28 18:15 UTC by Endermanbugzjfc

I found codes in InfoAPI are not easy to read. Reader might confuse with the context even though some places were seem to be self-explanatory.

For example, I spent some time trying understand why had you done this:
https://github.com/Endermanbugzjfc/InfoAPI/blob/comment-like-ima-noob/src/SOFe/InfoAPI/Ast/InfoSegment.php#L53-L54

2022-12-28 18:25 UTC, Endermanbugzjfc commented
Sorry, forgot to re-fork before starting the branch.

I forked a long time ago. I do not even commit to a fork's default branch nowadays.

2022-12-29 02:16 UTC, SOF3 commented on src/SOFe/InfoAPI/Ast/ChildName.php
>  	}
Actually I am a bit confused about this function now. Are we checking if `$this` is subsequence of `$pattern`, or `$pattern` is subsequence of `$this`? The documentation states the former, but the code appears to be the latter.

2022-12-29 02:29 UTC, SOF3 requested changes

2022-12-29 02:29 UTC, SOF3 commented on src/SOFe/InfoAPI/Ast/Expression.php
> +	 */
```suggestion
	/** Candidates of coalescence paths in a linked list. */
```

2022-12-29 02:29 UTC, SOF3 commented on src/SOFe/InfoAPI/Ast/InfoSegment.php
> +	 * (An {@link Expression->alternative} holds the next coalescence path.)
```suggestion
	 * Linked list of the coalescence path.
	 * @see Expression->alternative
```

2022-12-29 02:29 UTC, SOF3 commented on src/SOFe/InfoAPI/Ast/InfoSegment.php
> +	 * @param string $string Content in a brace-pair among segments in InfoAPI template string.
```suggestion
	 * @param string $string The substring inside braces
```

2022-12-29 02:29 UTC, SOF3 commented on src/SOFe/InfoAPI/Ast/InfoSegment.php
> +	 * @param int $index Where does a path starts in its superstring.
```suggestion
	 * @param int $index Starting index of `$string` in the template.
```

2022-12-29 02:29 UTC, SOF3 commented on src/SOFe/InfoAPI/Ast/InfoSegment.php
> +	 * @param int $index Where does a path starts in its superstring.
```suggestion
	 * @param int $index Starting index of `$path` in the template string.
```

2022-12-29 02:29 UTC, SOF3 commented on src/SOFe/InfoAPI/Ast/InfoSegment.php
>  		$expr = $head;
```suggestion
		// `$expr` is the tail of the linked list of expressions.
		$expr = $head;
```

2022-12-29 02:29 UTC, SOF3 commented on src/SOFe/InfoAPI/Ast/InfoSegment.php
> +				// Support two or more coalescence paths:
```suggestion
				// Update the tail of the linked list
```

2022-12-29 02:29 UTC, SOF3 commented on src/SOFe/InfoAPI/Ast/InfoSegment.php
> +			// +1 to include the "|" of path separation:
```suggestion
			// +1 to include the "|" separator
```

2022-12-29 02:29 UTC, SOF3 commented on src/SOFe/InfoAPI/Ast/InfoSegment.php
> +	 * @param string $path Reminder: paths in a superstring are separated by "|".
```suggestion
	 * @param string $path A path string separated by `|` in an info segment.
```

2022-12-29 02:29 UTC, SOF3 commented on src/SOFe/InfoAPI/Ast/Segment.php
> + * Either a `TextSegment` or an `InfoSegment`. (Just like enums.)
Is this comment really helpful?

2022-12-29 02:29 UTC, SOF3 commented on src/SOFe/InfoAPI/Ast/TextSegment.php
> + * (The segment that InfoAPI ignore.)
InfoAPI doesn't ignore it; InfoAPI still has to include this text.
```suggestion
 * A segment of (escapes-resolved) plain-text that gets appended to the output directly.
```

2022-12-29 07:57 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/Ast/ChildName.php
>  	}
I think the code states the former too. Why do you think that?

2022-12-29 07:58 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/Ast/InfoSegment.php
>  		$expr = $head;
Thank you, was thinking if I should add this too.

2022-12-29 07:59 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/Ast/Segment.php
> + * Either a `TextSegment` or an `InfoSegment`. (Just like enums.)
It could act as a double-confirmation for people who know enum.

2022-12-29 11:04 UTC, SOF3 commented on src/SOFe/InfoAPI/Ast/Segment.php
> + * Either a `TextSegment` or an `InfoSegment`. (Just like enums.)
I think this is just more confusing, especially when "enum" means different things in different languages. For example PHP enums are just constants.

2022-12-30 17:11 UTC, Endermanbugzjfc commented on src/SOFe/InfoAPI/Ast/Segment.php
> + * Either a `TextSegment` or an `InfoSegment`. (Just like enums.)
```suggestion
 * Either a `TextSegment` or an `InfoSegment`.
```
👍 ?

2023-08-13 04:38 UTC, SOF3 commented
Closed since I rewrote the entire thing #29. Feel free to add more comments if the new code is confusing.

2023-08-13 04:38 UTC, closed without merging